### ISSUE TITLE
Displaying layer images to mariner

### ISSUE THREAD

**Issue by macskay** [BlueFinBima/mariner#1]
**Preface**
First off let me tell you that I came across your fork because of the fact, that I'm using a Mars Pro on 4.4.3 and it works awesomely. Good work on the patches here. So now onto my Feature Request.

**Is your feature request related to a problem? Please describe.**
No, there is no problem but rather an idea.

**Describe the solution you'd like**
I wonder if it was possible to extract the layer images from that are shown on the Mars Pro Display upon each stage to also display in mariner. As far as I understood all information regarding the print are stored within the ctb/cbddlp file as it gives the printer the information which UV LEDs to lighten up. So it needs to be in there somewhere. I haven't looked into the details of the implementation of mariner so far but I assume this should be somewhat possible as "Current Layer", "Remaining Time" etc. are also read out by mariner.

**Describe alternatives you've considered**
Another idea would be to actually manually capture images of the chitubox slicing procedure, either in 3d or the actual print view and be able to upload a zipped image with numbered images to mariner. I imagine something like "print_1_1.png, print_1_2.png, print_1_3.png" along with the "print1.ctb". Marina could then extract the zip and when the print is started have lookup table to see which image to show in the nodejs frontend. What are your thoughts on either idea?

**Comment by macskay** [comment]
I've done a bit of research on this and as far as I see it this should be possible with cbddlp files but not with ctb's. There are various cbddlp "viewers" out there on Github that also show the images. We'd have to dig into their code and see how to read it out I assume. However it should be possible after all.

**Comment by macskay** [comment]
As a reference this might be something worth looking into: https://github.com/Photonsters/PhotonFileValidator/blob/0a91b655a5e6602546cbfe812306c3ed79cb03ee/src/photon/file/parts/PhotonFileLayer.java#L209

In there the image is read out byte by byte from the cbddlp file. Maybe this can be done in mariner as well. The header is read out by mariner already as meta information is shown by mariner. Should be possible to find the layer offset and then read the layers in as well byte by byte converting the information into a bit-array and plotting the bit-array with matplotlib or the like.

**Comment by BlueFinBima** [comment]
Hi Max, This fork is purely tactical to cope with 4.4.3 in the short term.  Once the original Mariner3D project can cope with the firmware, this fork will be discontinued.  As such, no feature requests are being accepted on this fork.  Can I suggest you raise the feature request with the Mariner3D project?
Thanks for your thoughts.
